# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Unnati Palan
title: Data Analyst
email: unnati.palan@gmail.com
website: https://unnatipalan.github.io/

# Social links
twitter_username: datakitten
github_username:  unnatipalan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: unnati-palan
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Data Analyst & Report Developer with Research Background in <mark>Cognitive Science</mark>, comfortable with visualization of business data in <mark>Tableau</mark>. With data insights, I help businesses succeed.

  I am most skilled in: <mark>Tableau</mark> and <mark>SQL</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
